const { test } = require('node:test')
const assert = require('node:assert/strict')
const { readFileSync } = require('node:fs')
const { join } = require('node:path')
const { parse, compileScript, compileTemplate } = require('@vue/compiler-sfc')

test('propagation evidence dialog compiles and supports source paging and request race protection', () => {
  const source = readFileSync(join(__dirname, '../src/components/PropagationEvidenceDialog.vue'), 'utf8')
  const { descriptor, errors } = parse(source)
  assert.deepEqual(errors, [])
  const script = compileScript(descriptor, { id: 'evidence' })
  const template = compileTemplate({ id: 'evidence', source: descriptor.template.content, filename: 'PropagationEvidenceDialog.vue', compilerOptions: { bindingMetadata: script.bindings } })
  assert.deepEqual(template.errors, [])
  assert.match(source, /id === requestId/)
  assert.match(source, /propagation-evidence/)
  assert.match(source, /el-pagination/)
  assert.match(source, /https:/)
  assert.match(source, /未经显著性检验/)
})
test('each summary has a distinct evidence entry and does not label cumulative heat as peak', () => {
  const source = readFileSync(join(__dirname, '../src/views/PlatformSpreadView.vue'), 'utf8')
  for (const mode of ['lead', 'heat', 'span', 'relations']) assert.ok(source.includes(`evidenceMode = '${mode}'`))
  assert.match(source, /累计热度最高/)
  assert.match(source, /最早达到阈值/)
  assert.match(source, /lead_platforms/)
})
